.TH "hub-help" "1" "13 Feb 2019" "hub version 2.9.0" "Show the help page for a command."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub help\fR hub
.br
\fB\fChub help\fR \fICOMMAND\fP
.br
\fB\fChub help\fR hub\-\fICOMMAND\fP [\-\-plain\-text]
.SH "OPTIONS"
.PP
hub\-\fICOMMAND\fP
.RS 4
Use this format to view help for hub extensions to an existing git command.
.RE
.PP
\-\-plain\-text
.RS 4
Skip man page lookup mechanism and display plain help text.
.RE
.br
.SH "LOOKUP MECHANISM"
.P
On systems that have \fB\fCman\fR, help pages are looked up in these directories
relative to the hub install prefix:
.IP \(bu 2.3
man/\fIcommand\fP.1
.sp -1
.IP \(bu 2.3
share/man/man1/\fIcommand\fP.1
.br
.P
On systems without \fB\fCman\fR, help pages are looked up using the ".txt" extension.
.SH "SEE ALSO"
.P
hub(1), git\-help(1)

