.TH "hub-init" "1" "13 Feb 2019" "hub version 2.9.0" "Initialize a git repository and add a remote pointing to GitHub."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub init\fR \-g
.SH "OPTIONS"
.PP
\-g
.RS 4
After initializing the repository locally, add the "origin" remote pointing
to "\fIUSER\fP/\fIREPO\fP" repository on GitHub.
.sp
\fIUSER\fP is your GitHub username, while \fIREPO\fP is the name of the current
working directory.
.RE
.br
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub init \-g
> git init
> git remote add origin git@github.com:USER/REPO.git
.fi
.RE
.SH "SEE ALSO"
.P
hub\-create(1), hub(1), git\-init(1)

