.TH "hub-push" "1" "13 Feb 2019" "hub version 2.9.0" "Push a git branch to each of the listed remotes."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub push\fR \fIREMOTE\fP[,\fIREMOTE2\fP...] [\fIREF\fP]
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub push origin,staging,qa bert\_timeout
> git push origin bert\_timeout
> git push staging bert\_timeout
> git push qa bert\_timeout

$ hub push origin
> git push origin HEAD
.fi
.RE
.SH "SEE ALSO"
.P
hub(1), git\-push(1)

