.TH "hub-delete" "1" "13 Feb 2019" "hub version 2.9.0" "Delete an existing repository on GitHub."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub delete\fR [\-y] [\fIORGANIZATION\fP/]\fINAME\fP
.SH "OPTIONS"
.PP
\-y, \-\-yes
.RS 4
Skip the confirmation prompt and immediately delete the repository.
.RE
.PP
[\fIORGANIZATION\fP/]\fINAME\fP
.RS 4
The name for the repository on GitHub.
.RE
.br
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub delete recipes
[ personal repo deleted on GitHub ]

$ hub delete sinatra/recipes
[ repo deleted in GitHub organization ]
.fi
.RE
.SH "SEE ALSO"
.P
hub\-init(1), hub(1)

