.TH "hub-fetch" "1" "13 Feb 2019" "hub version 2.9.0" "Add missing remotes prior to performing git fetch."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub fetch\fR \fIUSER\fP[,\fIUSER2\fP...]
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub fetch \-\-multiple jingweno mislav
> git remote add jingweno git://github.com/jingweno/REPO.git
> git remote add mislav git://github.com/mislav/REPO.git
> git fetch jingweno
> git fetch mislav
.fi
.RE
.SH "SEE ALSO"
.P
hub\-remote(1), hub(1), git\-fetch(1)

