.TH "hub-submodule" "1" "13 Feb 2019" "hub version 2.9.0" "Add a git submodule for a GitHub repository."
.nh
.ad l
.SH "SYNOPSIS"
.P
\fB\fChub submodule\fR add [\-p] [\fIOPTIONS\fP] [\fIUSER\fP/]\fIREPOSITORY\fP \fIDESTINATION\fP
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub submodule add jingweno/gh vendor/gh
> git submodule add git://github.com/jingweno/gh.git vendor/gh
.fi
.RE
.SH "SEE ALSO"
.P
hub\-remote(1), hub(1), git\-submodule(1)

